# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/001-FlyFast-demo-app" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/104-opentelemetry-zipkin-nodejs-app" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/105-opentelemetry-go-app" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/106-opentelemetry-autoinstrumentation-java-app" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/107-opentelemetry-autoinstrumentation-nodejs-app" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/108-collect-zipkin-nodejs-app" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/109-opentelemetry-export" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/111-opentelemetry-autoinstrumentation-spring-demo-app" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/202-instrument-java-app-with-apm-agentless-in-container" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/203-instrument-java-app-with-apm-agent-in-container" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/233-instrument-java-app-with-apm-agentless-on-gke" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/238-instrument-java-app-with-apm-daemonset-pod-agent-on-gke" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "203-instrument-java-app-with-apm-agent-in-container/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "238-instrument-java-app-with-apm-daemonset-pod-agent-on-gke/app"
    schedule:
      interval: "weekly"
      

